"""
Base de datos de componentes HBA/HBD, NADES de tesis y polifenoles objetivo.

Polifenoles EP basados en:
  Ruiz et al. (2024) Horticulturae 10, 458 — Tabla 2
  "Calafate (Berberis microphylla G. Forst) Populations from Chilean Patagonia
   Exhibit Similar Structuring at the Genetic and Metabolic Levels"

Polifenoles NEP: modelo teórico (sin literatura previa para Berberis + NADES).
"""

import pandas as pd

# ─────────────────────────────────────────────────────────────────
# COMPONENTES HBA (Aceptores de Puente de Hidrógeno)
# ─────────────────────────────────────────────────────────────────
HBA_COMPONENTS = {
    "Cloruro de Colina (ChCl)": {
        "mw": 139.6,
        "polarity": 0.60,
        "hbd": 2,
        "hba": 5,
        "antioxidant": 0.10,
        "viscosity_ref": 200,
        "precio_usd_kg": 15,
        "descripcion": "Sal de amonio cuaternario; el HBA más usado en NADES. GRAS.",
    },
    "Betaína": {
        "mw": 117.1,
        "polarity": 0.65,
        "hbd": 1,
        "hba": 4,
        "antioxidant": 0.25,
        "viscosity_ref": 300,
        "precio_usd_kg": 35,
        "descripcion": "Aminoácido natural (remolacha); alternativa sin halógenos al ChCl.",
    },
    "Prolina": {
        "mw": 115.1,
        "polarity": 0.68,
        "hbd": 3,
        "hba": 4,
        "antioxidant": 0.35,
        "viscosity_ref": 500,
        "precio_usd_kg": 90,
        "descripcion": "Aminoácido cíclico; alta afinidad con compuestos fenólicos.",
    },
    "Ácido Láctico (como HBA)": {
        "mw": 90.1,
        "polarity": 0.70,
        "hbd": 2,
        "hba": 3,
        "antioxidant": 0.50,
        "viscosity_ref": 40,
        "precio_usd_kg": 18,
        "descripcion": "Actúa como HBA frente a poliales; carbonilo acepta H-bonds. 100% natural.",
    },
    "L-Carnitina": {
        "mw": 161.2,
        "polarity": 0.68,
        "hbd": 2,
        "hba": 5,
        "antioxidant": 0.30,
        "viscosity_ref": 400,
        "precio_usd_kg": 55,
        "descripcion": "Aminoácido zwitteriónico similar a betaína; GRAS; buena compatibilidad con fenólicos.",
    },
    "Taurina": {
        "mw": 125.1,
        "polarity": 0.72,
        "hbd": 3,
        "hba": 5,
        "antioxidant": 0.20,
        "viscosity_ref": 350,
        "precio_usd_kg": 28,
        "descripcion": "Aminosulfónico natural; grupo sulfónico da alta capacidad HBA; 100% natural. "
        "Ref: Hayyan et al. 2013 Ind. Eng. Chem. Res. 52(44), 16311.",
    },
    "L-Lisina": {
        "mw": 146.2,
        "polarity": 0.75,
        "hbd": 3,
        "hba": 5,
        "antioxidant": 0.20,
        "viscosity_ref": 350,
        "precio_usd_kg": 45,
        "descripcion": "Aminoácido esencial (diaminoácido); alta afinidad iónica con ácidos fenólicos; "
        "100% natural; GRAS. Ref: Hayyan et al. 2013 Ind. Eng. Chem. Res.",
    },
    "Etanolamina": {
        "mw": 61.1,
        "polarity": 0.71,
        "hbd": 2,
        "hba": 4,
        "antioxidant": 0.15,
        "viscosity_ref": 21,
        "precio_usd_kg": 12,
        "descripcion": "Amino alcohol; bajo PM, muy baja viscosidad, reduce viscosidad total del NADES. "
        "Ref: Francisco et al. 2012 Green Chem. 14, 2153.",
    },
    "Trigonelina": {
        "mw": 137.1,
        "polarity": 0.70,
        "hbd": 1,
        "hba": 4,
        "antioxidant": 0.30,
        "viscosity_ref": 400,
        "precio_usd_kg": 120,
        "descripcion": "Alcaloide natural del café; forma NADES estables con azúcares y ácidos; "
        "actividad antioxidante propia. Ref: Ruesgas-Ramón et al. 2017 J. Agric. Food Chem.",
    },
    "Colina (base libre)": {
        "mw": 121.2,
        "polarity": 0.63,
        "hbd": 2,
        "hba": 4,
        "antioxidant": 0.12,
        "viscosity_ref": 220,
        "precio_usd_kg": 18,
        "descripcion": "Base libre de colina (sin haluro); menor salinidad que ChCl; "
        "mejor para extractos alimentarios. Ref: Durand et al. 2013 ChemSusChem 6, 1–20.",
    },
    "Betaína Anhidra": {
        "mw": 117.1,
        "polarity": 0.65,
        "hbd": 1,
        "hba": 4,
        "antioxidant": 0.28,
        "viscosity_ref": 280,
        "precio_usd_kg": 30,
        "descripcion": "Forma anhidra de betaína; mayor concentración activa; osmoprotector natural. "
        "Ref: Paiva et al. 2014 ACS Sustainable Chem. Eng. 2(5), 1063.",
    },
    # ── Terpenoides — HDES (eutécticos HIDROFÓBICOS) ──────────────
    # Forman fase única entre sí y con ácidos de cadena corta/media,
    # NO con azúcares, polioles ni ácidos polihidroxilados.
    # `hidrofobico: True` activa el modelo de saturación de agua en model.py.
    "Timol (como HBA)": {
        "mw": 150.2,
        "polarity": 0.32,
        "hbd": 1,
        "hba": 2,
        "antioxidant": 0.80,
        "viscosity_ref": 30,
        "precio_usd_kg": 40,
        "hidrofobico": True,
        "descripcion": "Monoterpeno fenólico (tomillo/orégano); rol HBA frente a ácidos carboxílicos. "
        "Base de HDES; antioxidante fenólico propio; GRAS (FEMA 3066). "
        "Ref: Martins et al. 2018 ACS Sustain. Chem. Eng. 6, 8836.",
    },
    "Mentol": {
        "mw": 156.3,
        "polarity": 0.28,
        "hbd": 1,
        "hba": 2,
        "antioxidant": 0.20,
        "viscosity_ref": 45,
        "precio_usd_kg": 32,
        "hidrofobico": True,
        "descripcion": "Monoterpeno alcohólico; socio clásico del timol (HDES mentol:timol 1:1, "
        "líquido a T amb.); GRAS. Ref: Ribeiro et al. 2015 ACS Sustain. Chem. Eng. 3, 2469.",
    },
    "Alcanfor": {
        "mw": 152.2,
        "polarity": 0.25,
        "hbd": 0,
        "hba": 2,
        "antioxidant": 0.15,
        "viscosity_ref": 90,
        "precio_usd_kg": 22,
        "hidrofobico": True,
        "descripcion": "Monoterpeno cetónico; HBA puro (sin OH) para HDES con timol; "
        "mezcla más viscosa y volátil que mentol:timol. "
        "Ref: Martins et al. 2018 ACS Sustain. Chem. Eng. 6, 8836.",
    },
}

# ─────────────────────────────────────────────────────────────────
# COMPONENTES HBD (Donadores de Puente de Hidrógeno)
# ─────────────────────────────────────────────────────────────────
HBD_COMPONENTS = {
    "Ácido Ascórbico (Vit. C)": {
        "mw": 176.1,
        "polarity": 0.87,
        "hbd": 5,
        "hba": 6,
        "antioxidant": 0.95,
        "pH_puro": 2.6,
        "viscosity_ref": 650,
        "acidic": True,
        "precio_usd_kg": 22,
        "descripcion": "⭐ Antioxidante más potente disponible; protege antocianinas activamente; "
        "quelante de Fe³⁺; pH ácido ideal para EP+NEP simultáneo.",
    },
    "Ácido Málico": {
        "mw": 134.1,
        "polarity": 0.82,
        "hbd": 4,
        "hba": 5,
        "antioxidant": 0.72,
        "pH_puro": 2.5,
        "viscosity_ref": 1100,
        "acidic": True,
        "precio_usd_kg": 22,
        "descripcion": "Diácido natural, excelente HBD, quelante de metales pro-oxidantes.",
    },
    "Ácido Láctico": {
        "mw": 90.1,
        "polarity": 0.70,
        "hbd": 2,
        "hba": 3,
        "antioxidant": 0.50,
        "pH_puro": 2.3,
        "viscosity_ref": 40,
        "acidic": True,
        "precio_usd_kg": 18,
        "descripcion": "Bajo PM, muy fluido, pH ácido excelente para antocianinas.",
    },
    "Ácido Cítrico": {
        "mw": 192.1,
        "polarity": 0.80,
        "hbd": 5,
        "hba": 7,
        "antioxidant": 0.82,
        "pH_puro": 2.1,
        "viscosity_ref": 900,
        "acidic": True,
        "precio_usd_kg": 12,
        "descripcion": "Triácido, máxima cap. HBD, potente quelante metálico (Fe³⁺, Cu²⁺).",
    },
    "Ácido Succínico": {
        "mw": 118.1,
        "polarity": 0.78,
        "hbd": 3,
        "hba": 4,
        "antioxidant": 0.40,
        "pH_puro": 2.8,
        "viscosity_ref": 500,
        "acidic": True,
        "precio_usd_kg": 32,
        "descripcion": "Diácido de metabolismo celular; PM bajo; buena fluidez; natural (Krebs).",
    },
    "Ácido Oxálico": {
        "mw": 90.0,
        "polarity": 0.82,
        "hbd": 2,
        "hba": 4,
        "antioxidant": 0.35,
        "pH_puro": 1.5,
        "viscosity_ref": 300,
        "acidic": True,
        "precio_usd_kg": 15,
        "descripcion": "pH muy bajo; máxima hidrólisis de NEP; vigilar degradación de antocianinas.",
    },
    "Ácido Tartárico": {
        "mw": 150.1,
        "polarity": 0.82,
        "hbd": 4,
        "hba": 6,
        "antioxidant": 0.60,
        "pH_puro": 2.4,
        "viscosity_ref": 1000,
        "acidic": True,
        "precio_usd_kg": 28,
        "descripcion": "Ácido de uva, natural, biodegradable y antioxidante moderado.",
    },
    "Ácido Levulínico": {
        "mw": 116.1,
        "polarity": 0.68,
        "hbd": 2,
        "hba": 3,
        "antioxidant": 0.15,
        "pH_puro": 3.1,
        "viscosity_ref": 50,
        "acidic": True,
        "precio_usd_kg": 45,
        "descripcion": "Derivado de biomasa (furfural); líquido a T amb.; puede disrumpir "
        "interacciones proteína-polifenol por su cadena alifática.",
    },
    "Ácido Acético": {
        "mw": 60.1,
        "polarity": 0.65,
        "hbd": 1,
        "hba": 2,
        "antioxidant": 0.20,
        "pH_puro": 2.9,
        "viscosity_ref": 15,
        "acidic": True,
        "precio_usd_kg": 10,
        "descripcion": "Muy volátil; fácil eliminación posterior; baja capacidad HBD.",
    },
    "Glicerol": {
        "mw": 92.1,
        "polarity": 0.70,
        "hbd": 3,
        "hba": 5,
        "antioxidant": 0.10,
        "pH_puro": 6.5,
        "viscosity_ref": 1412,
        "acidic": False,
        "precio_usd_kg": 12,
        "descripcion": "Triol clásico; DES más estudiado; compatible con flavonoides y HCADs.",
    },
    "1,2-Propilenglicol (PD)": {
        "mw": 76.1,
        "polarity": 0.60,
        "hbd": 2,
        "hba": 4,
        "antioxidant": 0.10,
        "pH_puro": 7.0,
        "viscosity_ref": 56,
        "acidic": False,
        "precio_usd_kg": 20,
        "descripcion": "Diol de bajo PM; muy fluido; GRAS; reduce viscosidad del sistema.",
    },
    "Xilitol": {
        "mw": 152.1,
        "polarity": 0.86,
        "hbd": 5,
        "hba": 5,
        "antioxidant": 0.15,
        "pH_puro": 7.0,
        "viscosity_ref": 4000,
        "acidic": False,
        "precio_usd_kg": 40,
        "descripcion": "Pentitol (5C); menor PM que sorbitol/manitol → mejor penetración de pared celular; "
        "alta polaridad; 100% natural.",
    },
    "Eritritol": {
        "mw": 122.1,
        "polarity": 0.85,
        "hbd": 4,
        "hba": 4,
        "antioxidant": 0.10,
        "pH_puro": 7.0,
        "viscosity_ref": 1800,
        "acidic": False,
        "precio_usd_kg": 35,
        "descripcion": "Tetritol (4C); PM muy bajo entre los poliales → excelente penetración celular; "
        "100% natural (fermentación). Prometedor para NEP.",
    },
    "Glucosa": {
        "mw": 180.2,
        "polarity": 0.85,
        "hbd": 5,
        "hba": 6,
        "antioxidant": 0.20,
        "pH_puro": 6.0,
        "viscosity_ref": 10000,
        "acidic": False,
        "precio_usd_kg": 8,
        "descripcion": "Alta cap. HBD y polaridad; requiere calentamiento por alta viscosidad.",
    },
    "Fructosa": {
        "mw": 180.2,
        "polarity": 0.85,
        "hbd": 5,
        "hba": 6,
        "antioxidant": 0.20,
        "pH_puro": 5.8,
        "viscosity_ref": 8000,
        "acidic": False,
        "precio_usd_kg": 10,
        "descripcion": "Isómero de glucosa, ligeramente menos viscosa.",
    },
    "Urea": {
        "mw": 60.1,
        "polarity": 0.75,
        "hbd": 4,
        "hba": 3,
        "antioxidant": 0.00,
        "pH_puro": 7.0,
        "viscosity_ref": 100,
        "acidic": False,
        "precio_usd_kg": 5,
        "descripcion": "DES de referencia clásica con ChCl; alta cap. HBD, neutro.",
    },
    "Sorbitol": {
        "mw": 182.2,
        "polarity": 0.88,
        "hbd": 6,
        "hba": 7,
        "antioxidant": 0.20,
        "pH_puro": 6.3,
        "viscosity_ref": 15000,
        "acidic": False,
        "precio_usd_kg": 12,
        "descripcion": "Hexitol de máxima polaridad y HBD entre poliales; muy viscoso. "
        "Ref: Dai et al. 2013 Anal. Chim. Acta 766, 61.",
    },
    "Trehalosa": {
        "mw": 342.3,
        "polarity": 0.93,
        "hbd": 8,
        "hba": 11,
        "antioxidant": 0.25,
        "pH_puro": 6.5,
        "viscosity_ref": 25000,
        "acidic": False,
        "precio_usd_kg": 65,
        "descripcion": "Disacárido crioprotector (2 glucosas α-1,1); máxima HBD entre azúcares; "
        "excelente estabilizador de compuestos bioactivos y antocianinas. "
        "Ref: Maugeri & Domínguez de María 2012 RSC Adv. 2, 421.",
    },
    "Manitol": {
        "mw": 182.2,
        "polarity": 0.90,
        "hbd": 6,
        "hba": 7,
        "antioxidant": 0.15,
        "pH_puro": 6.5,
        "viscosity_ref": 12000,
        "acidic": False,
        "precio_usd_kg": 15,
        "descripcion": "Hexitol natural (isómero de sorbitol); crioprotector; "
        "alta polaridad y HBD; 100% natural y GRAS. "
        "Ref: Faggian et al. 2016 RSC Adv. 6, 54924.",
    },
    "Etilenglicol": {
        "mw": 62.1,
        "polarity": 0.58,
        "hbd": 2,
        "hba": 4,
        "antioxidant": 0.05,
        "pH_puro": 7.0,
        "viscosity_ref": 16,
        "acidic": False,
        "precio_usd_kg": 8,
        "descripcion": "Diol más simple; muy baja viscosidad; reduce fluidez del sistema; "
        "usar con moderación (menor perfil GRAS que propilenglicol). "
        "Ref: Abbott et al. 2004 Chem. Commun. 70.",
    },
    "Ácido Glutárico": {
        "mw": 132.1,
        "polarity": 0.78,
        "hbd": 3,
        "hba": 4,
        "antioxidant": 0.38,
        "pH_puro": 2.6,
        "viscosity_ref": 400,
        "acidic": True,
        "precio_usd_kg": 28,
        "descripcion": "Diácido C5 (ácido pentanodioico); metabolito vegetal; "
        "buen agente ácido para hidrólisis de NEP. "
        "Ref: Florindo et al. 2014 Fluid Phase Equilib. 383, 32.",
    },
    "Inositol": {
        "mw": 180.2,
        "polarity": 0.91,
        "hbd": 6,
        "hba": 6,
        "antioxidant": 0.18,
        "pH_puro": 6.8,
        "viscosity_ref": 8000,
        "acidic": False,
        "precio_usd_kg": 55,
        "descripcion": "Ciclohexanohexol (myo-inositol, vitamina B8); presente en frutas; "
        "H-bonds de alta calidad con flavonoides por geometría cíclica; "
        "100% natural y GRAS. Ref: Dai et al. 2013 Anal. Chim. Acta 766, 61.",
    },
    "Ácido Pirúvico": {
        "mw": 88.1,
        "polarity": 0.73,
        "hbd": 2,
        "hba": 3,
        "antioxidant": 0.30,
        "pH_puro": 2.4,
        "viscosity_ref": 20,
        "acidic": True,
        "precio_usd_kg": 35,
        "descripcion": "Alfa-cetoacido (metabolito central del ciclo de Krebs); "
        "bajo PM y muy fluido; pH ácido; antioxidante vía piruvato-H₂O₂. "
        "Ref: Krystof et al. 2018 Green Chem. 20, 1940.",
    },
    # ── Terpenoides / ácidos grasos — HDES (HIDROFÓBICOS) ─────────
    "Timol": {
        "mw": 150.2,
        "polarity": 0.32,
        "hbd": 1,
        "hba": 2,
        "antioxidant": 0.80,
        "pH_puro": 6.0,
        "viscosity_ref": 30,
        "acidic": False,
        "precio_usd_kg": 40,
        "hidrofobico": True,
        "descripcion": "⭐ Monoterpeno fenólico (Thymus/Origanum); OH fenólico donador (pKa 10.6 → "
        "NO acidifica el medio). Base de eutécticos hidrofóbicos (HDES) selectivos hacia "
        "agliconas y fenoles poco polares; antioxidante y antimicrobiano propio; GRAS. "
        "Ref: Martins et al. 2018 ACS Sustain. Chem. Eng. 6, 8836; "
        "Ribeiro et al. 2015 ACS Sustain. Chem. Eng. 3, 2469.",
    },
    "Ácido Decanoico (C10)": {
        "mw": 172.3,
        "polarity": 0.30,
        "hbd": 1,
        "hba": 2,
        "antioxidant": 0.05,
        "pH_puro": 4.9,
        "viscosity_ref": 8,
        "acidic": False,  # ácido graso: no protona el medio como los ácidos orgánicos cortos
        "precio_usd_kg": 9,
        "hidrofobico": True,
        "descripcion": "Ácido graso de cadena media (cáprico); socio HBD clásico del timol y del "
        "mentol en HDES de baja viscosidad; natural (coco/leche). "
        "Ref: Florindo et al. 2019 ACS Sustain. Chem. Eng. 7, 14054.",
    },
}

# Componentes hidrofílicos que SÍ forman fase única con terpenoides:
# ácidos carboxílicos de cadena corta documentados como socios de HDES de timol.
# Ref: Martins et al. 2018 ACS Sustain. Chem. Eng. 6, 8836 (timol + ác. orgánicos).
for _nombre in ("Ácido Láctico", "Ácido Acético", "Ácido Levulínico"):
    HBD_COMPONENTS[_nombre]["apto_hdes"] = True
HBA_COMPONENTS["Ácido Láctico (como HBA)"]["apto_hdes"] = True

# ─────────────────────────────────────────────────────────────────
# RATIOS DISPONIBLES HBA:HBD
# ─────────────────────────────────────────────────────────────────
RATIOS_DISPONIBLES = {
    "1:1": (1, 1),
    "1:2": (1, 2),
    "1:3": (1, 3),
    "1:4": (1, 4),
    "2:1": (2, 1),
    "3:1": (3, 1),
    "4:1": (4, 1),
    "5:1": (5, 1),
}

# ─────────────────────────────────────────────────────────────────
# LOS 6 NADES DE LA TESIS (Etapa 1 — Cribado comparativo)
# ─────────────────────────────────────────────────────────────────
THESIS_NADES = [
    {
        "nombre": "ChCl : Ác. Málico",
        "hba": "Cloruro de Colina (ChCl)",
        "hbd": "Ácido Málico",
        "ratio_hba": 1,
        "ratio_hbd": 1,
        "water_pct": 30,
        "referencia": "Martins et al. 2025 [37]",
        "color": "#2E86AB",
    },
    {
        "nombre": "ChCl : Ác. Láctico",
        "hba": "Cloruro de Colina (ChCl)",
        "hbd": "Ácido Láctico",
        "ratio_hba": 1,
        "ratio_hbd": 2,
        "water_pct": 30,
        "referencia": "Martins et al. 2025 [37]",
        "color": "#A23B72",
    },
    {
        "nombre": "Ác. Láctico : PD",
        "hba": "Ácido Láctico (como HBA)",
        "hbd": "1,2-Propilenglicol (PD)",
        "ratio_hba": 2,
        "ratio_hbd": 1,
        "water_pct": 30,
        "referencia": "Martins et al. 2025 [37]",
        "color": "#F18F01",
    },
    {
        "nombre": "ChCl : Glicerol",
        "hba": "Cloruro de Colina (ChCl)",
        "hbd": "Glicerol",
        "ratio_hba": 1,
        "ratio_hbd": 2,
        "water_pct": 30,
        "referencia": "Antileo-Laurie et al. 2025 [38]",
        "color": "#048A81",
    },
    {
        "nombre": "Ác. Láctico : Glucosa",
        "hba": "Ácido Láctico (como HBA)",
        "hbd": "Glucosa",
        "ratio_hba": 5,
        "ratio_hbd": 1,
        "water_pct": 20,
        "referencia": "Antileo-Laurie et al. 2025 [38]",
        "color": "#C44536",
    },
    {
        "nombre": "ChCl : Ác. Oxálico",
        "hba": "Cloruro de Colina (ChCl)",
        "hbd": "Ácido Oxálico",
        "ratio_hba": 1,
        "ratio_hbd": 1,
        "water_pct": 30,
        "referencia": "Martins et al. 2025 [37]",
        "color": "#6B4226",
    },
]


# ─────────────────────────────────────────────────────────────────
# POLIFENOLES DE Berberis microphylla G. Forst
# Fuente EP: Ruiz et al. 2024 — Tabla 2 (HPLC-DAD-ESI-MS/MS)
# Fuente NEP: modelo teórico (sin literatura previa para Berberis + NADES)
#
# Campos:
#   concentracion_max  : μmol/g peso fresco, máximo observado (Tabla 2)
#   concentracion_rel  : relativa a Dp-3-glu (referencia = 1.00)
#   is_major           : True si concentración_rel > 0.10
#   oh_groups          : grupos –OH libres (modelo de estabilidad)
#   binding_sites      : sitios de unión a pared celular (modelo NEP)
# ─────────────────────────────────────────────────────────────────
def get_polyphenol_database() -> pd.DataFrame:
    data = [
        # ══ ANTOCIANINAS — EP ══════════════════════════════════════════
        # Mayoritarias en frutos de calafate; Dp-3-glu es el compuesto
        # más abundante de toda la fracción fenólica (hasta 12.81 μmol/g)
        {
            "id": 1,
            "nombre": "Delfinidin-3-glucósido",
            "abrev": "Dp-3-glu",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 12.21,
            "concentracion_rel": 1.00,
            "polaridad_optima": 0.85,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 8,
            "peso_molecular": 465.4,
            "logP": -1.5,
            "oh_groups": 7,
            "binding_sites": 0,
            "color": "#5C00B5",
            "descripcion": "Antocianina MAYORITARIA del calafate (Tabla 2). "
            "Anillo B con 3 grupos OH libres (catecol + OH adicional). "
            "Principal responsable del color violeta intenso y la actividad TEAC.",
        },
        {
            "id": 2,
            "nombre": "Delfinidin-3-rutinosido",
            "abrev": "Dp-3-ru",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 1.57,
            "concentracion_rel": 0.12,
            "polaridad_optima": 0.87,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 9,
            "peso_molecular": 611.5,
            "logP": -2.0,
            "oh_groups": 9,
            "binding_sites": 0,
            "color": "#6A0DAD",
            "descripcion": "Derivado rutinosídico de delfinidin; más polar por el disacárido.",
        },
        {
            "id": 3,
            "nombre": "Cianidín-3-glucósido",
            "abrev": "Cy-3-glu",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 1.88,
            "concentracion_rel": 0.15,
            "polaridad_optima": 0.83,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 8,
            "peso_molecular": 449.4,
            "logP": -1.2,
            "oh_groups": 6,
            "binding_sites": 0,
            "color": "#C71585",
            "descripcion": "Segunda antocianina más abundante; color rojo-violáceo.",
        },
        {
            "id": 4,
            "nombre": "Cianidín-3-rutinosido",
            "abrev": "Cy-3-ru",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.37,
            "concentracion_rel": 0.03,
            "polaridad_optima": 0.85,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 9,
            "peso_molecular": 595.5,
            "logP": -1.7,
            "oh_groups": 8,
            "binding_sites": 0,
            "color": "#DB1E6E",
            "descripcion": "Forma rutinosídica de cianidín; menor concentración.",
        },
        {
            "id": 5,
            "nombre": "Petunidín-3-glucósido",
            "abrev": "Pt-3-glu",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 7.64,
            "concentracion_rel": 0.60,
            "polaridad_optima": 0.84,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 8,
            "peso_molecular": 479.4,
            "logP": -1.3,
            "oh_groups": 6,
            "binding_sites": 0,
            "color": "#8B008B",
            "descripcion": "Tercera antocianina más abundante; contribuye al tono azulado.",
        },
        {
            "id": 6,
            "nombre": "Petunidín-3-rutinosido",
            "abrev": "Pt-3-ru",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 1.92,
            "concentracion_rel": 0.15,
            "polaridad_optima": 0.86,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 9,
            "peso_molecular": 625.5,
            "logP": -1.8,
            "oh_groups": 8,
            "binding_sites": 0,
            "color": "#9400D3",
            "descripcion": "Forma rutinosídica de petunidín.",
        },
        {
            "id": 7,
            "nombre": "Peonidín-3-glucósido",
            "abrev": "Pe-3-glu",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.88,
            "concentracion_rel": 0.07,
            "polaridad_optima": 0.82,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 7,
            "peso_molecular": 463.4,
            "logP": -0.9,
            "oh_groups": 5,
            "binding_sites": 0,
            "color": "#DC143C",
            "descripcion": "Metilación en anillo B; menor polaridad que delfinidin.",
        },
        {
            "id": 8,
            "nombre": "Peonidín-3-rutinosido",
            "abrev": "Pe-3-ru",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.10,
            "concentracion_rel": 0.01,
            "polaridad_optima": 0.84,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 8,
            "peso_molecular": 609.5,
            "logP": -1.4,
            "oh_groups": 7,
            "binding_sites": 0,
            "color": "#E8355A",
            "descripcion": "Forma rutinosídica de peonidín; concentración muy baja.",
        },
        {
            "id": 9,
            "nombre": "Malvidín-3-glucósido",
            "abrev": "Mv-3-glu",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 7.29,
            "concentracion_rel": 0.57,
            "polaridad_optima": 0.82,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 7,
            "peso_molecular": 493.4,
            "logP": -0.8,
            "oh_groups": 5,
            "binding_sites": 0,
            "color": "#800080",
            "descripcion": "Cuarta antocianina relevante; dos metoxilos reducen polaridad relativa.",
        },
        {
            "id": 10,
            "nombre": "Malvidín-3-rutinosido",
            "abrev": "Mv-3-ru",
            "clase": "Antocianina",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 1.06,
            "concentracion_rel": 0.08,
            "polaridad_optima": 0.84,
            "pH_min": 1.0,
            "pH_max": 4.0,
            "hbd_necesario": 8,
            "peso_molecular": 639.5,
            "logP": -1.3,
            "oh_groups": 7,
            "binding_sites": 0,
            "color": "#9B30FF",
            "descripcion": "Forma rutinosídica de malvidín.",
        },
        # ══ FLAVONOLES — EP ════════════════════════════════════════════
        {
            "id": 11,
            "nombre": "Quercetín-3-rutinosido",
            "abrev": "Q-3-ru",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 0.74,
            "concentracion_rel": 0.06,
            "polaridad_optima": 0.74,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 7,
            "peso_molecular": 610.5,
            "logP": -0.4,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#DAA520",
            "descripcion": "Flavonol MAYORITARIO del calafate (Tabla 2). Alta actividad DPPH/FRAP.",
        },
        {
            "id": 12,
            "nombre": "Quercetín-3-galactosido",
            "abrev": "Q-3-gal",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 0.71,
            "concentracion_rel": 0.06,
            "polaridad_optima": 0.73,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 7,
            "peso_molecular": 464.4,
            "logP": 0.5,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#B8860B",
            "descripcion": "Segundo flavonol más abundante; galactosido más polar que glucosido.",
        },
        {
            "id": 13,
            "nombre": "Quercetín-3-glucósido",
            "abrev": "Q-3-glu",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.22,
            "concentracion_rel": 0.02,
            "polaridad_optima": 0.72,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 7,
            "peso_molecular": 464.4,
            "logP": 0.5,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#CD853F",
            "descripcion": "Forma glucosídica de quercetín.",
        },
        {
            "id": 14,
            "nombre": "Quercetín-3-malonilgalactosido",
            "abrev": "Q-3-mal-gal",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.11,
            "concentracion_rel": 0.01,
            "polaridad_optima": 0.75,
            "pH_min": 3.0,
            "pH_max": 7.0,
            "hbd_necesario": 8,
            "peso_molecular": 550.5,
            "logP": 0.1,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#D2691E",
            "descripcion": "Derivado malonilado; acilación aumenta su estabilidad.",
        },
        {
            "id": 15,
            "nombre": "Quercetín-3-malonilglucósido",
            "abrev": "Q-3-mal-glu",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.49,
            "concentracion_rel": 0.04,
            "polaridad_optima": 0.75,
            "pH_min": 3.0,
            "pH_max": 7.0,
            "hbd_necesario": 8,
            "peso_molecular": 550.5,
            "logP": 0.1,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#A0522D",
            "descripcion": "Derivado malonilado de Q-3-glu; presente en calafate de Aysén.",
        },
        {
            "id": 16,
            "nombre": "Isorhamnetín-3-rutinosido",
            "abrev": "Isorham-3-ru",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.43,
            "concentracion_rel": 0.03,
            "polaridad_optima": 0.72,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 6,
            "peso_molecular": 624.5,
            "logP": 0.8,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#BDB76B",
            "descripcion": "Derivado O-metilado de quercetín; característico de Chile Chico.",
        },
        {
            "id": 17,
            "nombre": "Isorhamnetín-3-galactosido",
            "abrev": "Isorham-3-gal",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.17,
            "concentracion_rel": 0.01,
            "polaridad_optima": 0.71,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 6,
            "peso_molecular": 478.4,
            "logP": 1.0,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#9ACD32",
            "descripcion": "Isorhamnetín galactosídico; marcador de muestras de Chile Chico.",
        },
        {
            "id": 18,
            "nombre": "Quercetín-3-rhamnosido",
            "abrev": "Q-3-rham",
            "clase": "Flavonol",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.58,
            "concentracion_rel": 0.05,
            "polaridad_optima": 0.73,
            "pH_min": 3.0,
            "pH_max": 7.5,
            "hbd_necesario": 6,
            "peso_molecular": 448.4,
            "logP": 0.7,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#808000",
            "descripcion": "Forma rhamnosídica; ramnosa es menos polar que glucosa.",
        },
        # ══ ÁCIDOS HIDROXICINÁMICOS (HCADs) — EP ══════════════════════
        {
            "id": 19,
            "nombre": "5-Cafeoilquínico (5-CQ)",
            "abrev": "5-CQ",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 2.33,
            "concentracion_rel": 0.18,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 8,
            "peso_molecular": 354.3,
            "logP": -0.4,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#8B4513",
            "descripcion": "HCAD más abundante del calafate (Tabla 2). = Ácido clorogénico. "
            "Estándar de referencia en Folin-Ciocalteu (TPC).",
        },
        {
            "id": 20,
            "nombre": "Cafeoilglucárico B (CGI-B)",
            "abrev": "CGI-B",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 1.88,
            "concentracion_rel": 0.15,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 372.28,
            "logP": -0.8,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#A0522D",
            "descripcion": "Segundo HCAD más abundante; éster de ácido cafeico y glucárico.",
        },
        {
            "id": 21,
            "nombre": "Cafeoilglucárico C (CGI-C)",
            "abrev": "CGI-C",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": True,
            "concentracion_max": 1.25,
            "concentracion_rel": 0.10,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 372.28,
            "logP": -0.8,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#C4723D",
            "descripcion": "Isómero C del cafeoilglucárico.",
        },
        {
            "id": 22,
            "nombre": "Cafeoilglucárico A (CGI-A)",
            "abrev": "CGI-A",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 1.07,
            "concentracion_rel": 0.08,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 372.28,
            "logP": -0.8,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#D2856B",
            "descripcion": "Isómero A del cafeoilglucárico.",
        },
        {
            "id": 23,
            "nombre": "4,5-Dicafeoilglucárico (4,5-DCQ)",
            "abrev": "4,5-DCQ",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.81,
            "concentracion_rel": 0.06,
            "polaridad_optima": 0.78,
            "pH_min": 2.0,
            "pH_max": 6.0,
            "hbd_necesario": 9,
            "peso_molecular": 534.43,
            "logP": -1.2,
            "oh_groups": 7,
            "binding_sites": 1,
            "color": "#8B6914",
            "descripcion": "Diéster cafeoílico; mayor capacidad antioxidante que monoacil.",
        },
        {
            "id": 24,
            "nombre": "Dicafeoilglucárico (DCgluc)",
            "abrev": "DCgluc",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.67,
            "concentracion_rel": 0.05,
            "polaridad_optima": 0.78,
            "pH_min": 2.0,
            "pH_max": 6.0,
            "hbd_necesario": 9,
            "peso_molecular": 534.43,
            "logP": -1.2,
            "oh_groups": 7,
            "binding_sites": 1,
            "color": "#A07830",
            "descripcion": "Isómero dicafeoílico.",
        },
        {
            "id": 25,
            "nombre": "3,5-Dicafeoilglucárico (3,5-DCQ)",
            "abrev": "3,5-DCQ",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.64,
            "concentracion_rel": 0.05,
            "polaridad_optima": 0.78,
            "pH_min": 2.0,
            "pH_max": 6.0,
            "hbd_necesario": 9,
            "peso_molecular": 534.43,
            "logP": -1.2,
            "oh_groups": 8,
            "binding_sites": 1,
            "color": "#7B5E22",
            "descripcion": "Diéster cafeoílico del ácido glucárico. La abreviatura 'DCQ' es "
            "la que usa Ruiz et al. 2024 Tabla 2, pero el compuesto que nombran es "
            "GLUCÁRICO, no quínico: de ahí venía el PM 516.4 (quínico) que tenía esta "
            "entrada. Glucárico = C24H22O14 = 534.43.",
        },
        {
            "id": 26,
            "nombre": "Cafeoilquínico (CQ)",
            "abrev": "CQ",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.51,
            "concentracion_rel": 0.04,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 354.3,
            "logP": -0.4,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#9E7038",
            "descripcion": "Isómero de ácido clorogénico.",
        },
        {
            "id": 27,
            "nombre": "4-Cafeoilquínico (4-CQ)",
            "abrev": "4-CQ",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.38,
            "concentracion_rel": 0.03,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 354.3,
            "logP": -0.4,
            "oh_groups": 5,
            "binding_sites": 1,
            "color": "#C4906E",
            "descripcion": "4-O-isómero del ácido clorogénico.",
        },
        {
            "id": 28,
            "nombre": "Cafeoilglucárico D (CGI-D)",
            "abrev": "CGI-D",
            "clase": "Ác. Hidroxicinámico",
            "tipo": "EP",
            "is_major": False,
            "concentracion_max": 0.29,
            "concentracion_rel": 0.02,
            "polaridad_optima": 0.80,
            "pH_min": 2.0,
            "pH_max": 6.5,
            "hbd_necesario": 7,
            "peso_molecular": 372.28,
            "logP": -0.8,
            "oh_groups": 4,
            "binding_sites": 1,
            "color": "#D4A06A",
            "descripcion": "Isómero D del cafeoilglucárico; menor concentración.",
        },
        # ══ NEP — POLIFENOLES NO EXTRAÍBLES ════════════════════════════
        # Sin literatura previa para Berberis microphylla + NADES.
        # Modelo teórico original. Concentraciones estimadas por analogía
        # con otras Berberis y bayas patagónicas.
        {
            "id": 29,
            "nombre": "Proantocianidina B1",
            "abrev": "PAC-B1",
            "clase": "Tanino Condensado",
            "tipo": "NEP",
            "is_major": True,
            "concentracion_max": None,
            "concentracion_rel": 0.40,
            "polaridad_optima": 0.82,
            "pH_min": 2.0,
            "pH_max": 5.0,
            "hbd_necesario": 9,
            "peso_molecular": 578.5,
            "logP": -0.5,
            "oh_groups": 10,
            "binding_sites": 7,
            "color": "#8B0000",
            "descripcion": "Dímero EC-C; unido a proteínas de pared celular vía 7 H-bonds. "
            "SIN LITERATURA previa para extracción con NADES en Berberis.",
        },
        {
            "id": 30,
            "nombre": "Proantocianidina B2",
            "abrev": "PAC-B2",
            "clase": "Tanino Condensado",
            "tipo": "NEP",
            "is_major": True,
            "concentracion_max": None,
            "concentracion_rel": 0.40,
            "polaridad_optima": 0.82,
            "pH_min": 2.0,
            "pH_max": 5.0,
            "hbd_necesario": 9,
            "peso_molecular": 578.5,
            "logP": -0.5,
            "oh_groups": 10,
            "binding_sites": 7,
            "color": "#DC143C",
            "descripcion": "Dímero CC; fuertemente asociado a polisacáridos de pared celular. "
            "Requiere disrumpir enlaces C–C interflavánicos (solo parcialmente).",
        },
        {
            "id": 31,
            "nombre": "Ácido Elágico",
            "abrev": "AE",
            "clase": "Tanino Hidrolizable",
            "tipo": "NEP",
            "is_major": True,
            "concentracion_max": None,
            "concentracion_rel": 0.25,
            "polaridad_optima": 0.78,
            "pH_min": 2.0,
            "pH_max": 6.0,
            "hbd_necesario": 8,
            "peso_molecular": 302.2,
            "logP": 1.0,
            "oh_groups": 4,
            "binding_sites": 3,
            "color": "#FF4500",
            "descripcion": "Liberado por hidrólisis ácida de elagitaninos; pH < 3 es clave.",
        },
        {
            "id": 32,
            "nombre": "Taninos Hidrolizables (totales)",
            "abrev": "TH-total",
            "clase": "Tanino Hidrolizable",
            "tipo": "NEP",
            "is_major": True,
            "concentracion_max": None,
            "concentracion_rel": 0.35,
            "polaridad_optima": 0.80,
            "pH_min": 1.5,
            "pH_max": 5.0,
            "hbd_necesario": 9,
            "peso_molecular": 1200.0,
            "logP": -1.0,
            "oh_groups": 20,
            "binding_sites": 10,
            "color": "#FF6347",
            "descripcion": "Fracción total de elagitaninos + galotaninos; polímeros esterificados "
            "a glucosa. Hidrólisis ácida libera ác. gálico y ác. elágico.",
        },
    ]
    return pd.DataFrame(data)

